import { OG_CARD_SLUGS, OG_CARD_VERSION } from "@/data/ogCards";
import type { ShareImage } from "@/lib/seo";

type PageCard = "destinations" | "packages" | "services" | "about" | "contact";

const size = { width: 1200, height: 627 } as const;

/** Share card for one of the fixed pages (generated by scripts/og/build_cards.py). */
export function pageCard(page: PageCard, alt: string): ShareImage {
  return { url: `/og/pages/${page}-${OG_CARD_VERSION}.jpg`, ...size, alt };
}

/**
 * Share card for a destination or package, or undefined when none has been
 * generated for that slug yet (e.g. one added in the admin since the last
 * run) — callers fall back to the item's own photo.
 */
export function entityCard(
  kind: "destinations" | "packages",
  slug: string,
  alt: string,
): ShareImage | undefined {
  const slugs: readonly string[] = OG_CARD_SLUGS[kind];
  if (!slugs.includes(slug)) return undefined;
  return { url: `/og/${kind}/${slug}-${OG_CARD_VERSION}.jpg`, ...size, alt };
}
