/**
 * One-time migration helper. Imports the real, already-authored content
 * straight from src/data/*.ts and prints SQL INSERT statements that load it
 * into the matching Supabase tables — so the migration is a direct copy of
 * the source files, not a manual re-transcription that could drift from
 * them. Run once via `npx tsx scripts/generate-seed-sql.ts > seed.sql`, then
 * apply seed.sql to the database and delete both files.
 */
import { destinations } from "../src/data/destinations";
import { services } from "../src/data/services";
import { testimonials } from "../src/data/testimonials";
import { faqs } from "../src/data/faqs";

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlStringArray(values: readonly string[]): string {
  const inner = values.map((v) => `"${v.replace(/"/g, '\\"').replace(/'/g, "''")}"`).join(",");
  return `'{${inner}}'`;
}

function sqlJsonb(value: unknown): string {
  return `${sqlString(JSON.stringify(value))}::jsonb`;
}

const lines: string[] = [];

lines.push("-- Generated by scripts/generate-seed-sql.ts — do not hand-edit.");
lines.push("begin;");

destinations.forEach((d, i) => {
  lines.push(`insert into public.destinations
  (slug, name, tier, region, tagline, intro, body, hero_image, card_image, gallery, places, experiences, facts, seasons, ideal_for, featured, display_order)
values (
  ${sqlString(d.slug)},
  ${sqlString(d.name)},
  ${sqlString(d.tier)},
  ${sqlString(d.region)},
  ${sqlString(d.tagline)},
  ${sqlString(d.intro)},
  ${sqlStringArray(d.body)},
  ${sqlString(d.heroImage)},
  ${d.cardImage ? sqlString(d.cardImage) : "null"},
  ${sqlStringArray(d.gallery)},
  ${sqlJsonb(d.places)},
  ${sqlJsonb(d.experiences)},
  ${sqlJsonb(d.facts)},
  ${sqlJsonb(d.seasons)},
  ${sqlStringArray(d.idealFor)},
  ${d.featured},
  ${i}
);`);
});

services.forEach((s, i) => {
  lines.push(`insert into public.services
  (slug, title, summary, detail, points, icon, display_order)
values (
  ${sqlString(s.slug)},
  ${sqlString(s.title)},
  ${sqlString(s.summary)},
  ${sqlString(s.detail)},
  ${sqlStringArray(s.points)},
  ${sqlString(s.icon)},
  ${i}
);`);
});

testimonials.forEach((t, i) => {
  lines.push(`insert into public.testimonials
  (quote, name, role, trip, display_order)
values (
  ${sqlString(t.quote)},
  ${sqlString(t.name)},
  ${sqlString(t.role)},
  ${sqlString(t.trip)},
  ${i}
);`);
});

faqs.forEach((f, i) => {
  lines.push(`insert into public.faqs
  (question, answer, display_order)
values (
  ${sqlString(f.question)},
  ${sqlString(f.answer)},
  ${i}
);`);
});

lines.push("commit;");

console.log(lines.join("\n\n"));
