// Generated by scripts/og/build_cards.py — do not edit by hand.
// Slugs that have a share card in public/og/. Anything missing falls back to its normal photo.
export const OG_CARD_VERSION = "v1";

export const OG_CARD_SLUGS = {
  destinations: ["europe", "japan", "bali", "dubai", "vietnam", "malaysia", "singapore", "maldives", "sri-lanka", "nepal", "thailand", "kenya", "kazakhstan", "saudi-arabia"],
  packages: ["japan", "thailand-phuket-krabi-festival", "vietnam-getaway"],
} as const;
